# 2.1 Create a function to convert DNA string into fasta format

def convert2fasta(sequence):

    for rows in range(60, len(sequence) + 60, 60):

        row_sequence = sequence[rows-60:rows].lower()

        print(str(rows - 59).rjust(len( str( len(sequence) + 60 ))), end='\t')

        for fragments in range(10, len(row_sequence) + 10, 10):

            split_sequence = row_sequence[fragments-10:fragments]
            print(split_sequence, end=' ')

        print('')

sequence = "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTAAAGTTCATTGGAACAGAAAGAAATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTAGTCAACTTGTTGAAGAGCTATTGAAAATCATTTGTGCTTTTCAGCTTGACACAGGTTTGGAGTATGCAAACAGCTATAATTTTGCAAAAAAGGAAAATAACTCTCCTGAACATCTAAAAGATGAAGTTTCTATCATCCAAAGTATGGGCTACAGAAACCGTGCCAAAAGACTTCTACAGAGTGAACCCGAAAATCCTTCCTTGCAGGAAACCAGTCTCAGTGTCCAACTCTCTAACCTTGGAACTGTGAGAACTCTGAGGACAAAGCAGCGGATACAACCTCAAAAGACGTCTGTCTACATTGAATTGGGATCTGATTCTTCTGAAGATACCGTTAATAAGGCAACTTATTGCAGTGTGGGAGATCAAG"

convert2fasta(sequence)

# 2.2 Convert DNA sequence into translated protein sequence

sequence = 'aggagtaagcccttgcaactggaaatacacccattg'

trans_seq = {}
trans_seq['F'] = 'TTT'
trans_seq['F'] = 'TTC'
print(trans_seq)