# 1.1 Find the square of the Hypotenus
a = 10
b = 12

c_squared = (a**2) + (b**2)

print(c_squared)

Answer = 244

# 1.2 Slicing challenge
string = "TheUniversityOfManchesterFacultyofBiologyMedicineAndHealth"
part_one = string[3:13]
part_two = string[15:25]

print(part_one, part_two)

sequence = "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTAAAGTTCATTGGAACAGAAAGAAATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTGAT"
part_one = sequence[137:143]
part_two = sequence[274:280]

print(part_one, part_two)

'''
[137:143] = GAAGAA
[274:280] = GAAGAA
'''

# 1.3 Sum of odd integers
total = 0
a = 10
b = 25

for n in range(a, b, 2):
    odd_number = n + 1
    total += odd_number

print(total)

Answer = 144

# 1.4 Print out blocks of DNA sequence
sequence = "aggagtaagcccttgcaactggaaatacacccattg"

for codon in range(0, len(sequence)+3, 3):
    print(sequence[codon-3:codon], end=' ')

sequence = "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTAAAGTTCATTGGAACAGAAAGAAATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTGAT"

for codon in range(0, len(sequence)+10, 10):
    print(sequence[codon-10:codon], end=' ')

# 1.5 Convert DNA into mRNA
DNA = "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTAAAGTTCATTGGAACAGAAAGAAATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTGAT"
RNA = DNA.replace("T", "U")

print(RNA)